### ISSUE TITLE
НУ ЧТО ПРИВЕТ

### ISSUE THREAD

**Issue by Vovo4k** [AleXTop1/StarOS#2]
ПРИВЕТ СРАННЫЙ УЁБОК КОТОРЫЙ МЕНЯ ПРОСТО ТАК ЗАБАНИЛ НА СЕРВЕРЕ

**Comment by AleXTop1** [comment]
Я тебя не просто так забанил на сервере, вместо того чтобы сказать мне что
я не настроил роль запинговал весь сервер поэтому забанил. И да, этим
сообщением ты показал мне свой менталитет, спс.

ср, 5 июл. 2023 г., 19:58 Vladimir Vlaicu ***@***.***>:

**Comment by Vovo4k** [comment]
Чел ты гений я написал это давно

**Comment by Vovo4k** [comment]
Ты же у нас типа самый умный

**Comment by Vovo4k** [comment]
Ты настолько умный что делаешь интриги

**Comment by AleXTop1** [comment]
Мне только сейчас пришло уведомление что ты мне это написал так что я не
виноват

ср, 23 авг. 2023 г., 09:36 Vladimir Vlaicu ***@***.***>:
